### PR TITLE
Fixed path to phantomjs, that stopped wallaby.js running

### PR DESCRIPTION
**Pull request by alicia-peters-dev**

### CODE REVIEW

**Comment by philipooo** [comment]
Hi @ceepeeuk 

The path `node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs` does not exists in my environment. Do you have any informations why there is a `bin` folder at yours?

Cheers
Philip

**Comment by ArtemGovorov** [comment]
Different paths are probably because of different OS.
You may use 

``` JavaScript
runner: require('phantomjs2-ext').path
```

as an OS agnostic way. I' have updated wallaby docs.

**Comment by philipooo** [comment]
Thanks @ceepeeuk for pointing this out. And thank you @ArtemGovorov for providing the solution!
I commited the solution to master and will close this PR.
Btw: I'am on windows.

**Comment by alicia-peters-dev** [comment]
Thanks both, works fine for me on osx with this change.

**Pull request closed without merging**
